# Data transformation

```{r, include=FALSE}
games <- read.csv("dataset/games.csv")
games <- games[-c(1,3,4,8,14,16)]
```

## Cleaning Rated Status
```{r}
library(stringr)
games$rated <- str_to_upper(games$rated)
table(games$rated)
```

## Cleaning Turns
```{r}
library(ggplot2)
ggplot(data = games, aes(x = turns)) + geom_histogram(bins = 50) +
  geom_vline(xintercept = 10, color = "red")

games <- games[games$turns >= 10,]
```


## Cleaning Users
```{r}
tb <- table(c(games$white_id, games$black_id))
tb <- tb[tb >= 3]
ggplot(as.data.frame(tb), aes(x = Freq)) + geom_histogram() + geom_vline(xintercept = 3, color = "red") +
  xlab("Number of games each player played")

games <- games[(games$white_id %in% names(tb) & games$black_id %in% names(tb) ),]
```

## Cleaning Opening Names
```{r}
games$opening_name <- str_split_fixed(games$opening_name, ":", n = 2)[,1]
games$opening_name <- str_split_fixed(games$opening_name, " [#|]", n = 2)[,1]
head(sort(table(games$opening_name), decreasing = T), n = 20)
```

## Head
```{r}
head(games)
```
```{r}
write.csv(games, "dataset/clean_games.csv")
```


