# Results

```{r, include=FALSE}
library(tidyr)
library(tidyverse)
library(ggplot2)
library(alr4)
library(dplyr)
library(hrbrthemes)
```

```{r}
# get clean dataset
clean_games <- read.csv("dataset/clean_games.csv")
```
Top 10 players in each ranks

```{r}
getMatchNum <- function(df, left, right){
  tempW <- df %>%
  group_by(white_id) %>% 
  filter(white_rating >= left & white_rating <right) %>% summarize(n = n())
  
  tempB <- df %>%
  group_by(black_id) %>% 
  filter(black_rating >= left & black_rating <right) %>% summarize(n = n())
  
  colnames(tempW)<- c("id", "match_num")
  colnames(tempB)<-c("id", "match_num")
  temp1<-bind_rows(tempW, tempB) %>%
    group_by(id) %>%
    summarise_all(sum)
  temp1<-filter(temp1, match_num>2)
  return(temp1)
}
```


```{r}
getWinNum <- function(df, left,right){
  tempW <- df %>%
    group_by(white_id) %>% 
    filter(white_rating >= left & white_rating <right & winner == "white") %>% summarize(n = n())
  
  tempB <- df %>%
    group_by(black_id) %>% 
    filter(black_rating >= left & black_rating <right & winner == "black") %>% summarize(n = n())
  
  colnames(tempW)<- c("id", "win_num")
  colnames(tempB)<-c("id", "win_num")
  temp2<-bind_rows(tempW, tempB) %>%
    group_by(id) %>%
    summarise_all(sum)
  return(temp2)
}
```

```{r}
rankPlayer<-function(df, left, right){
  temp1<-getMatchNum(df, left,right)
  temp2<-getWinNum(df,left,right)
  temp<-merge(temp1, temp2, by = "id", all.x = TRUE)
  
  temp[is.na(temp)]<-0
  temp$winning_rate = temp$win_num/temp$match_num
  temp<-temp[order(-temp$winning_rate),]
  return(temp)
}
```

```{r}
rank750<-rankPlayer(clean_games, 750, 1150)
rank750$level = "1"
rank1150<-rankPlayer(clean_games,1150,1549)
rank1150$level = "2"
rank1550<-rankPlayer(clean_games,1550,1949)
rank1550$level ="3"
rank1950<-rankPlayer(clean_games,1950, 2350)
rank1950$level ="4"
rank2350<-rankPlayer(clean_games, 2350,2750)
rank2350$level ="5"
rank<- rbind(rank750, rank1150,rank1550, rank1950, rank2350)
```
```{r}
ggplot(rank, aes(x = level, y = winning_rate, fill = level)) +
  geom_boxplot(alpha = 0.3, size = 0.75) + 
  ggtitle("Distribution of winning rate in each level") +
  labs(x = "Level", y = "Wining Rate", caption = "Source: https://www.kaggle.com/datasnaek/chess") +
  theme_bw() +
  theme(legend.position = "none",
    plot.title = element_text(face = "bold"), 
        plot.caption = element_text(color = "grey68")) +
  scale_fill_brewer(palette = "Blues")
```
```{r}
ggplot(rank, aes(x = factor(level), fill = level)) +
  geom_bar(alpha = 0.3, size = 0.75, color = "black") + 
  geom_text(stat = 'count', aes(label = ..count..), vjust = -0.7) +
  ylim(0,650) +
  ggtitle("Number of players in each level") +
  labs(x = "Level", y = "Number of Players", caption = "Source: https://www.kaggle.com/datasnaek/chess") +
  theme_bw() +
  theme(legend.position = "none",
    plot.title = element_text(face = "bold"), 
        plot.caption = element_text(color = "grey68")) +
  scale_fill_brewer(palette = "Blues")
```
```{r}
top15 <-rbind(rank750[order(-rank750$winning_rate),][1:15,],
              rank1150[order(-rank1150$winning_rate),][1:15,],
              rank1550[order(-rank1550$winning_rate),][1:15,],
              rank1950[order(-rank1950$winning_rate),][1:15,],
              rank2350[order(-rank2350$winning_rate),][1:15,])

ggplot(top15, aes(x = winning_rate, reorder(id, winning_rate))) +
  geom_point(size = 1) + 
  facet_wrap(~level, scales = "free", ncol = 3,
             )
```

```{r}
opening_win <- clean_games %>% group_by(winner) %>% count(opening_name, sort = TRUE)
opening_win <- opening_win[opening_win$winner != 'draw',]
top20 <- clean_games %>% count(opening_name, sort = TRUE) %>% head(20)

opening_win <- opening_win[opening_win$opening_name %in% top20$opening_name, ]

ggplot(opening_win, aes(reorder(opening_name,n), n, fill = winner)) +
  geom_col(position = "fill", color = "lightgray")+
  coord_flip()+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 15),
        axis.text = element_text(size = 8),
        axis.title = element_text(size = 8),
        legend.position = "bottom")+
  scale_fill_manual(values = c("black", "cornsilk"))+
  labs(y = "Winning Ratio", x = NULL, fill = "Winner",
       title = "Winning Probability of Openings") +
  guides(color = FALSE)
```



```{r}
sicilian <- clean_games[clean_games$opening_name == "Sicilian Defense",]

ggplot(sicilian, aes(x = white_rating, y = black_rating, color = winner, shape = winner))+
  geom_point(alpha = 0.8)+
  theme_minimal()+
  theme(
    legend.position = "bottom",
    plot.title = element_text(hjust = 0.5, face = "bold", size = 15),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 8)
    )+
  scale_color_brewer(palette = "Dark2")+
  labs(y = "Black Rating", x = "White Rating", color = "Winner", shape = "Winner",
       title = "Winner & Draw Rating with Sicilian Defense Opening")


sc_rank750 <- rankPlayer(sicilian, 750, 1150)
sc_rank750$level = "1"
sc_rank1150 <- rankPlayer(sicilian,1150,1549)
sc_rank1150$level = "2"
sc_rank1550 <- rankPlayer(sicilian,1550,1949)
sc_rank1550$level ="3"
sc_rank1950 <- rankPlayer(sicilian,1950, 2350)
sc_rank1950$level ="4"
sc_rank2350 <- rankPlayer(sicilian, 2350,2750)
sc_rank2350$level ="5"
sc_rank<- rbind(sc_rank750, sc_rank1150, sc_rank1550, sc_rank1950, sc_rank2350)

ggplot(sc_rank, aes(x = level, y = winning_rate, fill = level)) +
  geom_boxplot(alpha = 0.3, size = 1) + 
  ggtitle("Distribution of winning rate in each level") +
  labs(x = "Level", y = "Wining Rate", caption = "Source: https://www.kaggle.com/datasnaek/chess") +
  theme_ipsum() +
  theme(legend.position = "none",
    plot.title = element_text(face = "bold"), 
        plot.caption = element_text(color = "grey68")) +
  scale_fill_brewer(palette = "Blues")
```

